sebadob/rauthy

- rauthy-common/src/constants.rs
- rauthy-handlers/src/generic.rs
- rauthy-handlers/src/oidc.rs
- rauthy-models/Cargo.toml
- rauthy-models/src/language.rs
- rauthy-models/src/lib.rs
Add a `Language` enum and make it possible to detect the browsers native language on 2 ways:
1. priority: LOCALE cookie which overrides the `Accept-Language` header
2. priority: try to extract and match the `Accept-Language` header
> browser native language detection

- justfile
- rauthy-models/src/app_state.rs
This checks (and possibly panics) at startup, if the target database type / url matches the currently used rauthy image with the correct feature flags.
Since the drivers for SQLite and Postgres are compiled into both binaries to make the `DB_MIGRATE_FROM` work in any combination, without this check it would be possible to use a SQLite database with the `postgres` features enabled, which would cause errors at runtime when the first db specific query would be fired up (latest).
This check does panic at startup immediately and informs the user about the misconfiguration and logs a hint about the correct container image.
> target database check at startup

- Cargo.lock
- Cargo.toml
- frontend/src/components/account/AccMFA.svelte
- frontend/src/components/admin/users/UserInfo.svelte
- frontend/src/utils/dataFetching.js
- justfile
- migrations/postgres/7_passkey_features.sql
- migrations/sqlite/7_passkey_features.sql
- rauthy-handlers/src/oidc.rs
- rauthy-handlers/src/openapi.rs
- rauthy-handlers/src/users.rs
- rauthy-main/src/main.rs
- rauthy-models/src/app_state.rs
- rauthy-models/src/entity/clients.rs
- rauthy-models/src/entity/colors.rs
- rauthy-models/src/entity/refresh_tokens.rs
- rauthy-models/src/entity/sessions.rs
- rauthy-models/src/entity/user_attr.rs
- rauthy-models/src/entity/users.rs
- rauthy-models/src/entity/webauthn.rs
- rauthy-models/src/i18n/account.rs
- rauthy-models/src/migration/db_migrate.rs
- rauthy-models/src/request.rs
- rauthy-models/src/response.rs
- rauthy-service/src/auth.rs
- rauthy-service/src/client.rs
- rauthy-service/src/password_reset.rs
- rauthy.cfg
This will be a bigger PR.
The first step is to create a new passkeys table and do a programmatic migration from the `webauthn` table data.
Then, delete all old webauthn data and user sec_key foreign keys. This deletes basically any existing webauthn keys for all users. In the third step, migrate the rest of the application over to the new passkeys table.
> Prepare new passkey features

- rauthy-models/src/app_state.rs
When `LISTEN_SCHEME` is set to `https` the issuer URL is constructed using "http://" prefix, which doesn't seem right.
> Construct issuer correctly when https only serving is enabled

- Cargo.toml
That saves around 20% of the binary size in my case (55MiB → 44MiB)
> Make sure to strip binary when doing a release build

- Cargo.lock
- Cargo.toml
- justfile
- rauthy-models/src/app_state.rs
- rauthy-models/src/entity/dpop_proof.rs
- rauthy-models/src/entity/jwk.rs
- rauthy-models/src/entity/jwk_token_validation.rs
- rauthy-models/src/entity/mod.rs
This makes it possible to use `RS256`, `RS384` and `RS512` JWKs with DPoP tokens.
> Impl DPoP RSA validation

- rauthy-handlers/src/oidc.rs
- rauthy-handlers/src/openapi.rs
- rauthy-main/tests/handler_generic.rs
- rauthy-models/src/app_state.rs
- rauthy-models/src/entity/mod.rs
- rauthy-models/src/entity/scopes.rs
- rauthy-models/src/entity/well_known.rs
This is a preparation for the `webid` coming in the future.
This moves the `WellKnown` struct out of the `AppState` into its own entity.
The `supported_scopes` can and will be dynamically rebuilt depending on Scope updates.
This is a preparation step for the `webid` claim for Solid-OIDC which will come in the future.
> Move WellKnown into entity

- rauthy-models/src/entity/jwk.rs
This fixes a cache bug that was introduced with v0.18.0.
The skipping of `None` values for a JWKS produces cache errors when the result should be deserialized afterswards again.
Skipping these values was an optimization for cleaner responses in tests and was introduced with the DPoP test cases.
Reverting this change solves the cache error.
> fix jwks cache error

- Cargo.lock
- frontend/src/utils/helpers.js
- rauthy-handlers/src/users.rs
- rauthy-models/Cargo.toml
- rauthy-models/src/entity/webids.rs
- rauthy-models/src/i18n/account.rs
- rauthy-models/src/response.rs
- rauthy.cfg
It now parses and formats data in turtle, translating to and from n-triples when required.
> fix: take turtle as input for custom triples

- Cargo.lock
- rauthy-book/src/config/config.md
- rauthy-models/src/events/notifier.rs
- rauthy-models/src/response.rs
- rauthy.cfg
This PR introduces the new config variable `EVENT_MATRIX_ERROR_NO_PANIC`.
If set to `true`, Rauthy will not panic at startup, if it cannot connect to a configured Matrix server.
This solves a possible chicken and egg problem if you self-host Matrix and Rauthy is your OIDC provider at the same time.
> Impl opt panic on matrix error

- Cargo.toml
- justfile
- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-handlers/src/users.rs
- rauthy-models/src/entity/magic_links.rs
- rauthy-service/src/password_reset.rs
- rauthy.cfg
This PR add a new config variable to encounter some problems : 
```
#
#
#
UNSAFE_NO_RESET_BINDING=true
```
> Impl unsafe no reset binding

- Cargo.lock
- Cargo.toml
- rauthy-handlers/src/middleware/principal.rs
- rauthy-handlers/src/users.rs
- rauthy-models/src/entity/users.rs
- rauthy-models/src/entity/webauthn.rs
- rauthy-service/src/password_reset.rs
This is a bugfix for the case, when an already existing (old) user with registered passkeys wanted to perform a password reset, that was triggered by an admin. In this case, it would not be possible to do the request properly, if the user would use a fully cleaned up browser for the reset without any session cookies and stuff. The validation was basically too strict.
> Fix password reset with old passkey

- rauthy-client/Cargo.toml
- rauthy-client/README.md
This is the preparation to release the `rauthy-client` on crates.io
> Release `rauthy-client` v0.1.0

- Cargo.lock
- Cargo.toml
- rauthy-book/src/config/config.md
- rauthy-main/src/logging.rs
- rauthy-main/src/schedulers.rs
- rauthy-models/Cargo.toml
- rauthy-models/src/migration/mod.rs
- rauthy.cfg
This implements SQLite backups automatically being pushed to a configured S3 bucket.
The backups will always be encrypted and plain SQLite files are neither an option nor allowed.
It well append the file ending `.cryptr` to make it directly visible, that these files are encrypted.
Restoring from an encrypted S3 backup will come with another PR.
> Encrypted backups to S3

- CHANGELOG.md
- dev_notes.md
- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-main/src/main.rs
- rauthy-models/src/entity/users.rs
- rauthy.cfg
This is a preparation for upcoming resource and performance improvements.
Currently, users are cached together with other data. This is not an issue for smaller deployments with just a few hundred users. However, if the user count goes up, this can lead to more memory being used than expected.
A typical Rauthy deployment will have limited amounts of data in all cases, usually. Meaning, clients will most possibly not exceed a few handful ones. The same is true for groups, roles, scopes, and so on. The only thing that might scale up endlessly are the users. Because of this, users will have their own distinct cache in the future. This can be configured and customized to fit the deployments needs. For instance, if you want the most performance possible, provide more memory and cache possibly …
> Outsource users into separate cache

- CHANGELOG.md
- rauthy-models/src/entity/users.rs
Changes User lookups in cache / db to always be case-insensitive for a better UX.
> user lookup by email always case-insensitive

- CHANGELOG.md
- dev_notes.md
- frontend/src/utils/helpers.js
- migrations/postgres/16_additional_scopes.sql
- migrations/sqlite/16_additional_scopes.sql
- rauthy-handlers/src/openapi.rs
- rauthy-models/src/entity/well_known.rs
- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
This will add addtitional OIDC default claims and / or expand the current ones.
The newly available user values may be added to the ID token if requested via scope.
> Expand default scopes

- Cargo.lock
- Cargo.toml
- dev_notes.md
- frontend/package-lock.json
- justfile
- rauthy-main/src/main.rs
- rauthy-main/tests/handler_scopes.rs
- rauthy-models/Cargo.toml
- rauthy-models/src/response.rs
- rauthy-notify/Cargo.toml
- rauthy-service/src/auth.rs
Prepare the first v0.20.0 beta release.
This needs some real world testing before release, because it modifies sensitive parts of the database and is **not backwards-compatible** with any prior version.
> Prepare v0.20.0-beta1

- dev_notes.md
- rauthy-models/src/response.rs
- rauthy-service/src/auth.rs
Extents the `/userinfo` endpoint with the additional OIDC values that have been added with v0.20.0.  
This now also correctly respects the `scope` claim from the access token which is being used to fetch userinfo.
> Extent `/userinfo` and respect `scope` 

- frontend/src/components/account/AccInfo.svelte
- frontend/src/components/account/AccWebId.svelte
- frontend/src/utils/helpers.js
- rauthy-handlers/src/oidc.rs
- rauthy-models/src/lib.rs
- rauthy-models/src/request.rs
- rauthy-service/src/auth.rs
This PR will make Rauthy respect `max_age` during the GET `/authorize` and it will add `auth_time` to the ID token.
The `auth_time` might be slightly off in certainc cases at this moment. To get it 100% right, Rauthy would need another DB migration. This will however not be implemented now, because I would be forced to release a new minor version just because of this small thing.  
Everything is there and working and the accuracy of the `auth_time` will be improved with a future PR.
> Implement `max_age`  + `auth_time` during the auth flow

- dev_notes.md
- rauthy-service/src/auth.rs
This PR completes the leftover mandatory implementations to be compliant with the OIDC core spec.  
There are only two notes:
1. Not all `prompt` params are implemented. `none` and `login` work like expected. I am unsure, if I want to implement `consent` later on at all, because it does not make too much sense to me in case of Rauthy.  
Rauthys only purpose is to identify and authorize users. If you don't want a downstream application to have any additional information about you, then just don't fill out the optional fields.  
If for instance Github is your auth provider, then this is a whole different story. You provide a lot more information to Github than you would ever want a 3rd party client to get. In this case, a (selective) consent makes sense, so you know which data will be …
> Skip 2nd, unnecessary `redirect_uri` check 

- CHANGELOG.md
- dev_notes.md
- frontend/src/routes/oidc/authorize/+page.svelte
If the user does not already have a valid session, a downstream client can improve the login flow, if it knows the username / email from some other source.  
In this case, it may append `login_hint` to the params. This will be respected by the Rauthy UI and the given value will pre-fill the E-Mail input field. This way, the user needs to do one less step for the login.
> respect `login_hint` during authorization

- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
This fixes #263
The `sub` claim in the access token was mapped to the users email address, which was not correct. The `sub` from access and id token must be the same. The `sub` in both tokens contains the user ID, which is 100% stable, because the email might change over time.
The `uid` claim from the access token has been dropped, because the `sub` now contains this very value.
The access token has a new optional `email` claim, which will contain the users email, or the "old" `sub` value. This just makes a lot of sense to have it in the access token too, because it is needed in a lot of applications. The `email` however will only be present, if it has been requested by the scope and if the login flow is not `client_credentials`.
> Fix access token sub claim

- rauthy-main/src/main.rs
This hosts the `.well-known/openid-configuration` on the root path additionally.  
Actually, this is the "wrong" spot, because this should always exists at `<issuer_url>/.well-known/openid-configuration`.
But this is an additional host, which then redirects to all the correct locations.  
This should make it possible, that even when someone is not providing the correct issuer for downstream client auto-configurations, that it should still work and basically fix the users issue.
> Host `.well-known` additionally on root `/`

- Dockerfile
- dev_notes.md
- rauthy.deploy.cfg
This fixes a bug (will be tested and validated with the next nightly / beta build) with the default path to the DEV TLS certificates for testing inside the container image. This basically moves the `WORKDIR` to `/` to match the default testing config. With this in place, it should be able to start Rauthy for testing with DEV TLS certificates without specifying the path to them manually.
> bug: wrong default path to DEV TLS certs inside container image

- frontend/src/utils/webauthn.js
An earlier version of the Bitwarden passkey implementation seems to have had an error and not populate values correctly.
This could lead to Rauthy complaining and returning an error, because the implementation was not correctly done.
This never seen before case could lead the UI to get stuck and not show an error because of a missing error body.
I cannot reproduce the error, but I added additional catches in the UI which should cases like this in the future and return to the default view showing an error.
> catch flase impl of passkeys

- rauthy-client/Cargo.toml
- rauthy-client/examples/actix-web/Cargo.lock
- rauthy-client/examples/axum/Cargo.lock
- rauthy-client/examples/generic/Cargo.lock
- rauthy-client/justfile
- rauthy-client/src/handler/actix_web.rs
- rauthy-client/src/handler/axum.rs
- rauthy-client/src/handler/mod.rs
- rauthy-client/src/lib.rs
- rauthy-client/src/principal/mod.rs
- rauthy-client/src/token_set.rs
- include all the new additional id token claims from the last additions to rauthy
- additional validation that the `sub` claims from both access and id token do actually match
- internal improvements to not break things in the future by using more `enum`s instead of `bool`s
- update all dependencies to the current versions
> rauthy client v0.2.0

- .gitignore
- CONTRIBUTING.md
- justfile
Adds an additional `just` recipe called `verify`. Contributors can run this with
```
just verify
```
before submitting a PR to make sure everything is fine.
It may make sense to create some github actions when we get more contributors, but at this stage, they would actually slow things more down than help.
I also updated the section for submits in the contributing readme.
> Ci improvements

- rauthy-client/examples/actix-web/src/main.rs
- rauthy-client/examples/axum/src/main.rs
- rauthy-client/examples/generic/src/main.rs
- rauthy-client/src/oidc_config.rs
- rauthy-client/src/principal/mod.rs
- rauthy-client/src/provider.rs
This adds the ability to choose between `any`, `or`, `and` and `none` `JwtClaims`. This is helpful to set the `.is_admin` and `.is_user` field more flexibly.
> Feat: Add `ClaimMapping`

- justfile
- rauthy-main/Cargo.toml
- rauthy-main/src/main.rs
- rauthy-models/Cargo.toml
- rauthy-models/src/app_state.rs
- rauthy-models/src/entity/app_version.rs
- rauthy-models/src/entity/colors.rs
- rauthy-models/src/entity/db_version.rs
- rauthy-models/src/entity/logos.rs
- rauthy-models/src/entity/refresh_tokens.rs
- rauthy-models/src/entity/sessions.rs
- rauthy-models/src/entity/user_attr.rs
- rauthy-models/src/entity/users_values.rs
- rauthy-models/src/entity/webids.rs
- rauthy.cfg
This PR is about trying to not make the LSP freak out in clean environments.
This should make it easier for new contributors to get into the project.
We cannot simply set `DATABASE_URL` for instance for sqlx compile time checked queries, because we cannot use the `Any` driver. However, to be able to easily switch between databases in dev without the need to modify the config each time, `just` has been providing this information until now.  
This works fine, but it makes the rust LSP freak out each time in environments, where you cannot set vars without interfering with the default setup.
This PR is about exploring solutions to make getting into the project smoother for new contributors.
> DX: try to improve LSP freak out in clean environments

- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-common/src/error_response.rs
- rauthy-handlers/src/oidc.rs
- rauthy-handlers/src/openapi.rs
- rauthy-main/src/main.rs
- rauthy-main/tests/handler_auth.rs
- rauthy-models/src/response.rs
- rauthy-service/src/auth.rs
- rauthy.cfg
- rauthy.test.cfg
This is an implementation of a dedicated `/auth/v1/oidc/forward_auth` endpoint with support for optional trusted authn / authz headers (mentioned in #337 ).
This makes it possible to have a more feature rich integration with things like Traefik's ForwardAuth middleware and push trusted headers about the logged in user to downstream applications (if proxy is configured properly of course).
The following config values do exist now:
```
AUTH_HEADERS_ENABLE=true
AUTH_HEADER_USER=x-forwarded-user
AUTH_HEADER_ROLES=x-forwarded-user-roles
AUTH_HEADER_GROUPS=x-forwarded-user-groups
AUTH_HEADER_EMAIL=x-forwarded-user-email
AUTH_HEADER_EMAIL_VERIFIED=x-forwarded-user-email-verified
AUTH_HEADER_FAMILY_NAME=x-forwarded-user-family-name
AUTH_HEADER_GIVEN_NAME=x-forwarded-user-given-name …
```
> feat: trusted authn / authz headers

- frontend/src/routes/users/{id}/reset/reset/+page.svelte
- rauthy-models/src/i18n/password_reset.rs
Register a new user shows a `Password Reset`, this should not be the case. The String Should be in the i18n model as well. This MR is fixing this.
> fix: Title is always showing `Password Reset` for registration

- dev_notes.md
- migrations/postgres/22_users_created_at_index.sql
- migrations/sqlite/22_users_created_at_index.sql
- rauthy-common/src/constants.rs
- rauthy-handlers/src/generic.rs
- rauthy-handlers/src/users.rs
- rauthy-models/src/entity/continuation_token.rs
- rauthy-models/src/entity/mod.rs
- rauthy-models/src/entity/users.rs
- rauthy-models/src/request.rs
- rauthy.cfg
This will add dynamic server side pagination and search functionality for the users page in the Admin UI.  
For bigger instances with many thousands of users, this will become more important, so the UI does not need to fetch all the users each time.
All the other "fetch all" endpoints will stay pretty small anyway, so there is no need to do this server side, since client side is usually more responsive and provides a better UX.
> feat: dynamic server side pagination + search for users

- rauthy-client/Cargo.toml
- rauthy-client/README.md
- rauthy-client/examples/actix-web/Cargo.lock
- rauthy-client/examples/axum/Cargo.lock
- rauthy-client/src/cookie_state.rs
- rauthy-client/src/device_code.rs
- rauthy-client/src/handler/actix_web.rs
- rauthy-client/src/handler/axum.rs
- rauthy-client/src/handler/mod.rs
- rauthy-client/src/jwks.rs
- rauthy-client/src/lib.rs
- rauthy-client/src/oidc_config.rs
- rauthy-client/src/principal/mod.rs
- rauthy-client/src/provider.rs
- rauthy-client/src/rauthy_error.rs
- rauthy-client/src/token_set.rs
This PR drops `anyhow` from `rauthy-client`. It should not be used in a crate. Instead we get a new `RauthyError` error type which converts easily into anything else.
> rauthy-client: drop `anyhow` in favor of `RauthyError` + `thiserror`

- rauthy-common/src/utils.rs
Switches the log level for failed peer ip extraction from the custom header from `error` to `debug`.  
The current setup will spam the logs if you have for instance a ready check inside kubernetes which of course does not have this custom header.
> switch log level for failed custom peer ip header extraction

- rauthy-handlers/src/clients.rs
Another typo in the spec. Seems utoipa does not check syntax in these bits either.
I also noticed that the openapi spec does not mention authentication so the swagger-ui does not offer a field for the API key to use for testing and that the calls do not mention which API key permission they need (though that should be fairly obvious) in the generated docs.
I am not far enough yet to know if the missing authentication part will become a problem for generating the Terraform provider but if it does I can patch it locally for now and let you know.
> Fix typos in openapi spec /clients/{id}}/colors -> /clients/{id}/colors

- rauthy-client/Cargo.toml
- rauthy-client/examples/device-code/Cargo.toml
- rauthy-client/examples/device-code/src/main.rs
- rauthy-client/src/device_code.rs
- rauthy-client/src/rauthy_error.rs
Makes it possible to generate a qrcode from a `verification_uri_full` returned during the Device Authorization Grant flow.
#369
> feat: `DeviceCode` verification uri -> qrcode

- rauthy-main/tests/handler_api_keys.rs
- rauthy-models/src/entity/principal.rs
Adds some additional docs on internal session validation fn's, simplifies some of them to make them more readable and mainatainable and return `HTTP 401` in some places where it makes more sense than an `HTTP 403`.
> Internal Improvements

- CHANGELOG.md
- dev_notes.md
- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
- rauthy-service/src/token_set.rs
- rauthy.cfg
This PR will take care of adding the device_id from the `device_code` flow to the `access_token`.
This will make it possible to later do an online verification when such an access token is used on the `/userinfo` endpoint and actually check, that the device still exists even when the token is still valid.
> add `device_id` to `access_token` for `/userinfo` online verification

- CHANGELOG.md
- dev_notes.md
- rauthy-client/src/token_set.rs
- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
- rauthy-service/src/token_set.rs
This will add the `at_hash` claim to the `id_token` for additional downstream validation, that a received `id_token` actually belongs to a specific `access_token`.
> feat: add `at_hash` to the `id_token`

- frontend/src/components/admin/groups/GroupConfig.svelte
- frontend/src/components/admin/roles/RoleConfig.svelte
- frontend/src/components/admin/scopes/ScopeConfig.svelte
- frontend/src/utils/constants.js
- migrations/postgres/24_roles_groups_scopes_limit.sql
- migrations/sqlite/24_roles_groups_scopes_limit.sql
- rauthy-common/src/constants.rs
- rauthy-models/src/request.rs
This will take care of a few things:
- remove the length limitations in the database for roles, groups and scopes (the API does full validation already)
- allow 64 instead of 32 long names on the api for these
- allow `:` to be contained in the names as well
- fix / adopt all other places where these changes cause issues
The reason behind this is to allow roles and groups names with a `:`, which can give you a bit nicer names, so you can have a better separation between different apps. For instance you could have roles like `app1:admin`, `app1:user`, `app2:admin`, ... .  
The fix for the scope especially makes it possible to allow longer scope names as well like `urn:ietf:params:oauth:grant-type:device_code` or `urn:matrix:client:api:guest`.
> Adjust validation for `roles`, `groups` and `scopes` names

- CHANGELOG.md
- frontend/src/components/admin/groups/GroupConfig.svelte
- frontend/src/components/admin/groups/GroupTileAddNew.svelte
- frontend/src/components/admin/roles/RoleConfig.svelte
- frontend/src/components/admin/roles/RoleTileAddNew.svelte
- frontend/src/components/admin/scopes/ScopeConfig.svelte
- frontend/src/components/admin/scopes/ScopeTileAddNew.svelte
- frontend/src/lib/itemTiles/ItemTiles.svelte
- frontend/src/utils/constants.js
- rauthy-common/src/constants.rs
- rauthy-models/src/request.rs
This will allow `*` as being valid inside scope names as well to allow `urn:matrix:client:api:*` and it does does some pre-request input string validation for roles, groups and scopes names in case a user has copied a value with trailing spaces.
> Expand scope groups roles validation - additions

- CHANGELOG.md
- dev_notes.md
- frontend/src/components/account/AccInfo.svelte
- frontend/src/components/account/AccMain.svelte
- frontend/src/lib/Modal.svelte
- frontend/src/routes/oidc/authorize/+page.svelte
- frontend/src/routes/providers/callback/+page.svelte
- frontend/src/utils/dataFetching.js
- rauthy-common/src/constants.rs
- rauthy-handlers/src/auth_providers.rs
- rauthy-handlers/src/lib.rs
- rauthy-main/src/main.rs
- rauthy-models/src/entity/auth_providers.rs
- rauthy-models/src/i18n/account.rs
- rauthy-models/src/i18n/index.rs
- rauthy-models/src/lib.rs
- rauthy.cfg
The "unlink" from upstream auth provider already exsits.
This PR will take care about the possibility to link an existing, un-linked account to a configured upstream auth provider.
> feat: link provider to existing account

- rauthy-client/Cargo.toml
- rauthy-client/src/provider.rs
The `device_code` grant contains `:` from the RFC spec and could therefore not be deserialized into the current enum.
This PR changes the Enum to a String for the deserialization to support the new type and make the client to not crash.
> client: fix `device_grant` JWKS deserialization error with rauthy 0.23.0-beta1

- Cargo.lock
- Cargo.toml
- dev_notes.md
- rauthy-models/src/entity/webauthn.rs
- rauthy-models/src/migration/db_migrate.rs
- rauthy.cfg
Internal migration of `webauthn-rs` to v0.5.  
We will have another beta release just to be 100% sure that no existing keys break with the migration.
> Migrate to webauthn-rs:0.5 and prepare v0.23.0-beta2

- CONTRIBUTING.md
- justfile
- rauthy.cfg
Add some improvements and fix typical errors on other platforms than Linux when running the `just` recipes.
This also fully gets rid of the additional `DEV_HOST` variable. This is now deferred automatically from the `PUB_URL`.
> Justfile improvements

- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-handlers/src/generic.rs
- rauthy-main/src/main.rs
- rauthy-service/src/aggressive_scan_block.rs
- rauthy-service/src/lib.rs
- rauthy.cfg
I recently see an increase in automated scanning in access logs from bots and other "people" for common misconfiguration, leaking secrets, and so on.  
This lead me to implementing a simple scanner in Rauthy's "catch all" route handler which will preemtively block IPs that do these scans. In the future these maybe can be reported automatically to [crowdsec](https://github.com/crowdsecurity/crowdsec).
There is a new config variable:
```
SUSPICIOUS_REQUESTS_BLACKLIST=1440
SUSPICIOUS_REQUESTS_LOG=true
```
> feat: suspicious req blacklist

- README.md
- dev_notes.md
- rauthy-book/src/config/config.md
- rauthy-common/src/constants.rs
- rauthy-handlers/src/generic.rs
- rauthy-handlers/src/lib.rs
- rauthy-handlers/src/middleware/principal.rs
- rauthy-handlers/src/oidc.rs
- rauthy-handlers/src/openapi.rs
- rauthy-handlers/src/users.rs
- rauthy-main/src/main.rs
- rauthy-main/tests/handler_auth.rs
- rauthy-main/tests/zza_handler_cust_attrs.rs
- rauthy-main/tests/zzc_handler_clients.rs
- rauthy-main/tests/zzz_ip_blacklist.rs
- rauthy-models/src/api_cookie.rs
- rauthy-models/src/entity/auth_providers.rs
- rauthy-models/src/entity/jwk.rs
- rauthy-models/src/entity/magic_links.rs
- rauthy-models/src/entity/sessions.rs
- rauthy-models/src/entity/webauthn.rs
- rauthy-models/src/language.rs
- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
- rauthy-service/src/password_reset.rs
- rauthy.cfg
Rauthy's cookie settings are now configurable to provide more flexibility depending on the final deployment and integration with possibly other apps hosted on the same domain or even origin.
The still unreleased `DANGER_COOKIE_INSECURE`  value has been removed again and instead we have 2 new config variables:
```
COOKIE_MODE=host
COOKIE_SET_PATH=true
```
> Feat: configurable cookie settings

- dev_notes.md
- rauthy-service/src/auth.rs
The `/userinfo` endpoint should client validation, if the client is ephemeral, since it does not make much sense to check an ephemeral client against the database.
> skip client validation on `/userinfo` if the client is ephemeral

- frontend/src/components/admin/userAttr/AttrTileAddNew.svelte
There was a small bug in the UI after adding new custom user attributes, which would set the input field values to `undefined` instead of an empty string during the reset.
> UI: set user attr values to empty string instead of undefined after add new

- rauthy-common/src/constants.rs
- rauthy-models/src/request.rs
When you are using playgrounds in the web, you might get very long URLs for your test-client config. When you try to use these with the ephemeral clients feature, they get rejected because they may exceed the 128 character limit. This has been doubled and should not cause any issues any more.
> allow longer `client_id`s for ephemeral clients

- rauthy-book/src/config/config.md
- rauthy-book/src/getting_started/k8s.md
- rauthy.cfg
- rauthy.deploy.cfg
- rauthy.test.cfg
The default values for password hashing should be bumped up to have at least somewhat "safe" values for production.
In the end, this highly depends on the deployment and a lot of factors, but these should give a better starting point.
> bump up argon2id defaults everywhere

- rauthy-common/src/error_response.rs
- rauthy-handlers/src/auth_providers.rs
- rauthy-handlers/src/lib.rs
- rauthy-handlers/src/oidc.rs
- rauthy-models/src/entity/app_version.rs
- rauthy-models/src/entity/auth_providers.rs
- rauthy-models/src/entity/clients.rs
- rauthy-models/src/entity/principal.rs
- rauthy-models/src/entity/sessions.rs
- rauthy-models/src/entity/users.rs
- rauthy-models/src/lib.rs
- rauthy-service/src/auth.rs
This PR is about simplifying the internal POST `/authorize` logic.  
The current code grew with additional features over time and became pretty hard to follow. This PR simplifies the code and fn's quite a bit to make it better maintainable and less error prone in the future.
> Simplify post authorize code

- frontend/src/routes/providers/callback/+page.svelte
#458 
Change the error message on the auth provider callback endpoint to make it easier to debug.  
If you get something like an HTTP 400, it is most often a provider error, because everything else is covered.  
This change will simply forward the backend error like it is.
> show the full backend error in the UI in case of a provider callback error

- Cargo.lock
- Cargo.toml
- rauthy-models/Cargo.toml
- rauthy-models/src/entity/auth_providers.rs
Sadly, we need to get rid of the string slice deserialization for upstream IdP tokens and move to `Cow<_>` and proper `String`s for compatibility reasons. When an upstream IdP does not use UTF8 characters but unicode encoding inside JWT's, `&'a str` deserialization will fail.
fixes #458
> Upstream IdP Tokens compatibility

- Cargo.lock
- Cargo.toml
- dev_notes.md
- rauthy.cfg
- src/api/src/clients.rs
- src/api/src/events.rs
- src/api/src/fed_cm.rs
- src/api/src/generic.rs
- src/api/src/oidc.rs
- src/api/src/users.rs
- src/common/Cargo.toml
- src/common/src/constants.rs
- src/common/src/utils.rs
- src/middlewares/src/csrf_protection.rs
- src/middlewares/src/ip_blacklist.rs
- src/middlewares/src/logging.rs
- src/middlewares/src/principal.rs
- src/models/src/entity/clients_dyn.rs
- src/models/src/entity/magic_links.rs
- src/models/src/entity/sessions.rs
- src/models/src/entity/users.rs
- src/models/src/events/event.rs
- src/models/src/templates.rs
- src/service/src/auth.rs
- src/service/src/password_reset.rs
To prevent client IP spoofing via headers with `PROXY_MODE=true` or a set `PEER_IP_HEADER_NAME´, `TRUSTED_PROXIES` is a new config var that needs to be set properly in the future.  
If any of these variables are set, `TRUSTED_PROXIES` is mandatory and Rauthy will only accept requests from direct sources inside `TRUSTED_PROXIES`.
The value accepts a list of multiple CIDR's, so you have all the flexibility you need.
> Feat `TRUSTED_PROXIES` config var

- Cargo.lock
- frontend/package-lock.json
- frontend/package.json
`vite-plugin-top-level-await` can't build of broken `@swc/core:1.7`
> ui: pin `@swc/core` to `v1.6.0` to fix upstream bug of missing type info

- CHANGELOG.md
- dev_notes.md
- src/bin/src/main.rs
The current behavior of reading in config variables was not working as intended.
Rauthy reads the `rauthy.cfg` as a file first and the environment variables afterward. This makes it possible to
configure it in any way you like and even mix and match.  
However, the idea was that any existing variables in the environment should overwrite config variables and therefore
have the higher priority. This was exactly the other way around up until `v0.24.1` and has been fixed now.
How Rauthy parses config variables now correctly:
1. read `rauthy.cfg`
2. read env var
3. all existing env vars will overwrite existing vars from `rauthy.cfg` and therefore have the higher priority
> fix: wrong config vars read priority

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- frontend/src/utils/dataFetchingAdmin.js
- frontend/vite.config.js
- src/api/src/oidc.rs
- src/bin/src/main.rs
- src/bin/tests/handler_auth.rs
- src/error/src/lib.rs
fixes #536
- `tokenInfo` -> `introspect` (done in PR #534 )
- `rotateJwk` -> `rotate_jwk`
Since I don't like `kebab-case`, most API routes are written in `snake_case`, with 2 exceptions that follow RFC namings:
- `openid-configuration`
- `web-identity`
All the `*info` routes are not `kebab_case` on purpose, just to match other IdPs and RFC a bit more.
There is not a single `camelCase` anymore in the API routes to avoid confusion and issues in situations where you could mistake an uppercase `I` as a lowercase `l`. The current `camelCase` endpoints only exist for a smoother migration and will be phased out with the next bigger release.
> fix API routes case differences

- frontend/src/components/account/AccInfo.svelte
- frontend/src/components/account/AccMain.svelte
- frontend/src/utils/constants.js
- src/api_types/src/generic.rs
- src/models/src/entity/well_known.rs
- src/models/src/i18n/account.rs
- src/models/src/i18n/authorize.rs
- src/models/src/i18n/device.rs
- src/models/src/i18n/email_change_info_new.rs
- src/models/src/i18n/email_change_info_old.rs
- src/models/src/i18n/email_confirm_change.rs
- src/models/src/i18n/email_confirm_change_html.rs
- src/models/src/i18n/email_password_new.rs
- src/models/src/i18n/email_reset.rs
- src/models/src/i18n/email_reset_info.rs
- src/models/src/i18n/error.rs
- src/models/src/i18n/index.rs
- src/models/src/i18n/logout.rs
- src/models/src/i18n/password_policy.rs
- src/models/src/i18n/password_reset.rs
- src/models/src/i18n/register.rs
- src/models/src/language.rs
This PR adds Simplified Chinese (zh-Hans) translations, and updates some English strings.
The next step is to let CJK characters not regarded as special character and add an option to make family name optional (Mongolian people does not have family names, and also some people may not want to use their real name).
> Add Simplified Chinese translations

- frontend/src/utils/constants.js
- src/common/src/constants.rs
This PR adds more code-blocks in Unicode Basic Multilingual Plane (BMP) to allow CJK characters.
This should include most of the common characters in names of who lives in East Asia.
Some symbols that should never appear in people's names are excluded.
> Allow more CJK characters to appear in user name

- book/src/SUMMARY.md
- book/src/config/config.md
- book/src/config/unix_socket.md
- justfile
- rauthy.cfg
- rauthy.deploy.cfg
- rauthy.test.cfg
- src/api/src/openapi.rs
- src/bin/src/main.rs
- src/bin/tests/common.rs
- src/common/src/constants.rs
- src/common/src/utils.rs
- src/models/src/app_state.rs
- src/models/src/entity/clients.rs
- src/models/src/i18n/account.rs
- src/models/src/i18n/email_reset.rs
- src/models/src/i18n/error.rs
- src/models/src/i18n/password_reset.rs
- src/models/src/lib.rs
This PR adds two `LISTEN_SCHEME` types: `unix_http`, `unix_https`.
They both create a UNIX socket of HTTP. The `http` and `https` are used to clarify the scheme to use for `PUB_URL`.
To test the UDS support, please use the following configuration:
```
LISTEN_SCHEME=unix_http
LISTEN_ADDRESS=server.sock
PEER_IP_HEADER_NAME=X-Forwarded-For
PUB_URL=localhost:8080
```
and start a reverse proxy, to turn UDS into TCP, for example, with caddy: `caddy reverse-proxy --from :8080 --to unix/server.sock`, or with socat: `socat UNIX-CLIENT:server.sock TCP-LISTEN:8080`.
Caddy is a real reverse proxy and it sends `X-Forwarded-For` header. socat is just a socket forwarder, so it does not send `X-Forwarded-For`. To use socat, `PEER_IP_HEADER_NAME` should be unset, and all users will be regarded as …
> Support listening on UNIX domain sockets

- src/models/src/entity/auth_providers.rs
Per RFC 8414 section 2, `code_challenge_methods_supported` is optional. It is missing in many OpenID servers.
> Make code_challenge_methods_supported optional

- src/api/src/auth_providers.rs
- src/api/src/openapi.rs
> Missing `/providers/{id}/link` doc

- book/src/getting_started/k8s.md
The same name for HTTP and HTTPS routes causes them to overwrite each other.
> fix the ingress name

- Cargo.lock
- Cargo.toml
- src/models/src/email.rs
- src/models/src/events/notifier.rs
There was a bug which made Rauthy not set the users actual name in the `to` field when sending out E-Mails, but actually the subject instead. Email sending was fine, because the address itself was correct, but the name was not.
> fix: set correct recipient name in email notifications

- src/api/src/generic.rs
- src/models/src/app_state.rs
- src/models/src/database.rs
- src/models/src/entity/users.rs
This will just make the `AppState.params` a bit simpler and better to read.
> unwrap the `Argon2Params` in `AppState`

- dev_notes.md
- migrations/hiqlite/1_init_schema.sql
- migrations/postgres/26_jwks_sig_ts_index.sql
Very tiny improvement for single JWK lookup (the table with will very small all the time), but it is basically for free.
> add an index for `(signatures, created_at)` on the `jwks` table

- dev_notes.md
- migrations/hiqlite/1_init_schema.sql
- migrations/postgres/27_idx_client_uris.sql
- rauthy.cfg
- src/api/src/users.rs
- src/common/src/constants.rs
- src/models/src/entity/clients.rs
- src/schedulers/src/passwords.rs
Follow-up for [#318](https://github.com/sebadob/rauthy/issues/318#issuecomment-2469259813)
A new config var will make it possible to restirect the possibilities of the `redirect_uri` param for the open user registration:
```
#
#
#USER_REG_OPEN_REDIRECT=true
```
> feat: disallow open redirect for `redirect_uri` with open user registration

- Cargo.lock
- Cargo.toml
- src/error/Cargo.toml
- src/error/src/error_impls.rs
- src/models/Cargo.toml
- src/models/src/entity/auth_providers.rs
- src/models/src/entity/logos.rs
Even though only the `rauthy_admin` role can upload SVG images for clients or upstream IdPs, they will from now on be sanitized as an additional defense in depth.
> feat: sanitize SVGs even though only admins can upload them

- book/src/config/user_reg.md
- frontend/src/utils/constants.js
- frontend/vite.config.js
- src/api_types/src/auth_providers.rs
- src/api_types/src/clients.rs
- src/api_types/src/users.rs
- src/common/src/constants.rs
fixes #614 
This PR will include `Latin-1 Extended A` alphabet in the regex validations for client readable name + user given and family names.
> add `Latin-1 Extended A` to the client and user names regex validations

- Cargo.lock
- Cargo.toml
- Dockerfile_builder
- dev_notes.md
- frontend/package-lock.json
- justfile
- rauthy.cfg
- rauthy.deploy.cfg
- src/api/src/auth_providers.rs
- src/api/src/clients.rs
- src/api/src/oidc.rs
- src/api/src/users.rs
- src/bin/src/main.rs
- src/common/src/constants.rs
- src/common/src/lib.rs
- src/models/src/database.rs
- src/models/src/entity/webauthn.rs
- src/models/src/entity/webids.rs
Rauthy is pretty close to the next release, dropping `sqlx::Sqlite` in favor of [Hiqlite](https://github.com/sebadob/hiqlite).
This migration was pretty huge and needs proper testing in advance, which this PR will take care of.
I still need to release a stable version of `hiqlite` before the next Rauthy release. With this PR I want to make sure, that no additions are needed on that front as well.
> bump deps and build nightly for Hiqlite testing

- src/bin/tests/handler_scopes.rs
- src/models/src/entity/clients.rs
- src/models/src/entity/scopes.rs
Fixes an issue with a new query implemented during the Hiqlite migration.
The query used `=` when it should have used `LIKE`. This made the query not return clients that needed an update because of a scope name change or deletion.
> fix: clients not being updated on custom scope update / delete

- frontend/src/components/admin/users/UserInfo.svelte
Addition for #627
Fix the `margin-top` and remove the `if` check for `User.created_At` -> this will value will always exist.
> fix: tiny display fix for `User.created_at` in admin ui

- book/src/SUMMARY.md
- docs/config/unix_socket.html
Fix tiny typo in "domain sockets"
> docs: fix typo in unix domain sockets

- src/bin/src/main.rs
- src/models/src/entity/password.rs
With the big migration to `hiqlite` under the hood, a bug has been introduced with v0.27.0 that made it possible to end up with a `NULL` value for the password policy after an update. This would result in errors further down the road after a restart, because the policy could not be read again.
This PR fixes this issue and does an additional check at startup (until v0.28.0), if the current deployment needs a fix for this issue. This means if you have a bad entry for it in your DB, just starting `0.27.1` will fix it.
> Fix: password policy update `NULL` value

- CHANGELOG.md
- Cargo.lock
- book/src/config/config.md
- rauthy.cfg
- src/api/src/oidc.rs
- src/common/src/constants.rs
- src/common/src/lib.rs
- src/service/src/token_set.rs
> feat: add `DISABLE_REFRESH_TOKEN_NBF` to disable `refresh_token.nbf`

- frontend/src/routes/users/register/+page.svelte
Tiny bugfix that allows nullable `family_name`s for the user registration form. The `family_name` has been made optional with the `v0.27` release.
> fix: allow nullable `family_name` for the registration form

- CHANGELOG.md
- src/models/src/entity/clients.rs
Fixes a bug during the deletion of a custom scope.
When you had a custom scope assigned to a client, but only added it to the `default_scopes` without allowing it for `scopes` in general, this mapping would get lost during the cleanup of the client mapping, when the custom scope has been deleted without removing the mapping first.
If this happened, you had to remove the scope mapping from the client manually to fix it.
This was due to a check if the to-be-deleted scope exists at all for this client and exit early if not. However, it is possible that a scope exists in default scopes only, so that the client does not have a choice and it will always be added. This has been fixed and an extra test case for this special case has been added as well.
> fix: client default scope cleanup

- justfile
> error: Justfile does not contain recipe `migrate`
Migration is done in `backend-start` -> `postgres-start` -> `migrate-postgres`
> fix: remove non-existent just migrate call

- Cargo.lock
- frontend/src/api/fetch.ts
- frontend/src/api/response/common/errorResponse.ts
> Svelte 5 Migration 3: create a new setup for type-safe API requests

- frontend/src/app.html
- frontend/src/components/Error.svelte
- frontend/src/components/account/AccPassword.svelte
- frontend/src/components/admin/AdminMainPre.svelte
- frontend/src/components/admin/ContentWrapper.svelte
- frontend/src/components/admin/clients/ClientBranding.svelte
- frontend/src/components/admin/clients/ClientSecret.svelte
- frontend/src/components/admin/events/Events.svelte
- frontend/src/components/admin/events/EventsArchive.svelte
- frontend/src/components/admin/users/UserForceLogout.svelte
- frontend/src/components/passwordReset/PasswordPolicy.svelte
- frontend/src/css/global.css
- frontend/src/global_state/is_dev.svelte.ts
- frontend/src/lib/nav/Nav.svelte
- frontend/src/lib_svelte5/ContentCenter.svelte
- frontend/src/lib_svelte5/Main.svelte
- frontend/src/routes/+layout.svelte
- frontend/src/routes/account/+page.svelte
- frontend/src/routes/device/+page.svelte
- frontend/src/routes/fedcm/+page.svelte
- frontend/src/routes/index/+page.svelte
- frontend/src/routes/oidc/authorize/+page.svelte
- frontend/src/routes/oidc/logout/+page.svelte
- frontend/src/routes/users/register/+page.svelte
- frontend/src/routes/users/{id}/email_confirm/email_confirm/+page.svelte
- frontend/src/routes/users/{id}/reset/reset/+page.svelte
- frontend/src/utils/dataFetching.js
- frontend/svelte.config.js
- frontend/vite.config.js
> Svelte 5 Migration 5: fixes after global CSS switch

- frontend/src/lib/LangSelector.svelte
- src/bin/src/main.rs
- src/bin/src/version_migration.rs
- src/models/src/language.rs
> fix: `zh-Hans` Hiqlite deserialization

- src/api/src/openapi.rs
- src/bin/src/main.rs
- src/models/src/app_state.rs
- src/models/src/entity/clients.rs
- src/models/src/lib.rs
As I have seen you added the fix in hiqlite to make it compatible with windows here:
https://github.com/sebadob/hiqlite/commit/c6113b57b96cae2551fa3c590bc97d11ee0c9e96
I thought maybe you would also add the small fixes in rauthy, as it is not much and would make life for me easier, so that I don't have to patch it ^^
The only thing left is to target the hiqlite branch with the fix currently
`hiqlite = { git = "https://github.com/sebadob/hiqlite.git", features = ["full"], rev = "626c6877c54f4c6bad360d02053853f6d3d4fefc" }`
as the latest commits had a problem that I think will be resolved in future:
`failed to select a version for `libsqlite3-sys``
> make compilable on windows removing unixsockets if windows

- Cargo.lock
- Cargo.toml
Even though the vulnerable code was not used, this fixes [CVE-2025-24898](https://nvd.nist.gov/vuln/detail/CVE-2025-24898)
> fix: bump `openssl` + `openssl-sys` to fix CVE-2025-24898

- rauthy-client/CHANGELOG.md
- rauthy-client/Cargo.toml
- rauthy-client/examples/actix-web/Cargo.lock
- rauthy-client/examples/actix-web/Cargo.toml
- rauthy-client/examples/actix-web/src/main.rs
- rauthy-client/examples/axum/Cargo.lock
- rauthy-client/examples/generic/Cargo.lock
- rauthy-client/examples/generic/src/main.rs
- rauthy-client/justfile
- rauthy-client/src/cookie_state.rs
- rauthy-client/src/lib.rs
- rauthy-client/src/rauthy_error.rs
Bumps dependencies for `rauthy-client`, mostly `ring` because of [CWE-770](https://github.com/advisories/GHSA-4p46-pwfr-66x6).
> rauthy-client: bump dependencies + MSRV

- rauthy.cfg
> fix: add the default `PUB_URL` for local dev in `rauthy.cfg` again

- frontend/src/i18n/common/de.ts
- frontend/src/i18n/common/en.ts
`Valid E-Mail Address` for the `email` input on the login page was a bit confusing and has now been changed to `Provide valid E-Mail address`.
> make i18n for `validEmail` more clear

- src/models/src/entity/magic_links.rs
To provide better debugging and error messages for improved UX, we will now always set `used = true` if `MagicLink::invalidate()` is being called. This also additionally prevents some weird situations we could get into with the expiry checker scheduler.
#796
> fix: set `used = true` during `MagicLink::invalidate()`

- rauthy.cfg
- src/models/src/entity/failed_backchannel_logout.rs
- src/models/src/entity/user_login_states.rs
- src/models/src/migration/db_migrate.rs
- src/models/src/migration/inserts.rs
Adds an additional safeguard for `MIGRATE_DB_FROM` that will panic if the feature is being used between different major / minor versions, which is not guaranteed to be stable all the time.
Also fixes some missing newer columns and tables and add them to the migration logic.
> feat: additional safeguards and fixes for `MIGRATE_DB_FROM`

- src/api/src/auth_providers.rs
- src/api/src/dev_only/dev_handler.rs
- src/api/src/oidc.rs
- src/models/src/entity/auth_providers.rs
- src/models/src/entity/clients.rs
- src/service/src/oidc/authorize.rs
- src/service/src/oidc/grant_types/authorization_code.rs
- src/service/src/oidc/grant_types/client_credentials.rs
- src/service/src/oidc/grant_types/password.rs
- src/service/src/oidc/grant_types/refresh_token.rs
- src/service/src/oidc/validation.rs
Rework the way the `origin` header is being checked and include `ADDITIONAL_ALLOWED_ORIGIN_SCHEMES` in tests to make sure it works as expected, as a preparation to add / fix CORS headers in some places.
> Rework the way the `origin` header is being checked 

- book/src/config/bootstrap.md
- book/src/config/config.md
- book/src/config/logging.md
- book/src/getting_started/first_start.md
- book/src/work/custom_scopes_attributes.md
- migrations/hiqlite/11_change_default_admin.sql
- migrations/postgres/V7__change_default_admin.sql
- rauthy-test.cfg
- rauthy.cfg
- src/bin/src/version_migration.rs
- src/bin/tests/common.rs
- src/bin/tests/handler_pwd_reset.rs
- src/bin/tests/handler_users.rs
- src/models/src/entity/clients_scim.rs
- src/models/src/entity/magic_links.rs
- src/models/src/entity/users.rs
- src/models/src/migration/init_prod.rs
To avoid potential conflicts with the default admin `admin@localhost.de`, it has been changed to `admin@localhost`.
The reason is, that `localhost.de` is a valid domain with an existing TLD. The reason it had the `.de` appended in the first place, is because the early validation for the username / email was very strict and required a TLD. This is not the case anymore and therefore made this change possible.
fixes #697
> Fix: change default admin

- frontend/src/api/types/auth_provider.ts
- frontend/src/api/types/authorize.ts
- frontend/src/routes/oidc/authorize/+page.svelte
- frontend/src/utils/pow.ts
- src/api/src/auth_providers.rs
- src/api/src/oidc.rs
- src/api_types/src/auth_providers.rs
- src/api_types/src/oidc.rs
To add additional protection against DoS, bots and automated security scanners, the `LoginRequest` + `ProviderLoginReqeust` now require a mandatory PoW. An additional benefit is, that an admin could shift a bit of resources for logins from the backend to the clients, when the `t_cost` for the password hashing (which always will be the bottleneck in terms of resources) is reduced slightly in exchange for a bit higher PoW difficulty.
> Feat: mandatory pow on `LoginRequest` + `ProviderLoginRequest`

- rauthy-client/CHANGELOG.md
- rauthy-client/Cargo.toml
- rauthy-client/examples/actix-web/Cargo.lock
- rauthy-client/examples/actix-web/src/main.rs
- rauthy-client/examples/axum/Cargo.lock
- rauthy-client/examples/axum/src/main.rs
- rauthy-client/examples/generic/Cargo.lock
- rauthy-client/examples/generic/src/main.rs
- rauthy-client/src/lib.rs
- rauthy-client/src/provider.rs
The `rauthy-client` was URL encoding the `redirect_uri` during the `/token` request, which could lead to invalid `redirect_uri` checks.
> rauthy-client: fix URL encoded `redirect_uri`

- src/middlewares/src/principal.rs
- src/models/src/entity/sessions.rs
Move "invalid state" logs for `SessionState` from `warn` into `debug` level and skip `Principal` extraction for static assets.
> Fix: logging for invalid `SessionState`

- src/models/src/migration/init_prod.rs
fixes #908
Because of the default admin renaming in `0.29`, which also renamed the test accs, they have not been deleted when starting a new prod instance.
> Fix: test acc deletion query for prod

- src/bin/src/main.rs
> Fix: change logging to `eprintln` if there was a config read error

- book/src/config/production_config.md
the link to the "Reference Config" is not correct here:
https://sebadob.github.io/rauthy/config/production_config.html
leads to:
https://sebadob.github.io/config/config.html
should:
https://sebadob.github.io/rauthy/config/config.html
> [Book] fix link to config

- CHANGELOG.md
- rauthy-client/Cargo.toml
- rauthy-client/examples/axum/Cargo.lock
- rauthy-client/examples/axum/Cargo.toml
- rauthy-client/examples/axum/README.md
- rauthy-client/examples/axum/src/main.rs
- rauthy-client/examples/axum/src/scim/groups.rs
- rauthy-client/examples/axum/src/scim/mod.rs
- rauthy-client/examples/axum/src/scim/users.rs
- rauthy-client/examples/axum/src/templates.rs
- rauthy-client/examples/generic/Cargo.lock
- rauthy-client/justfile
- rauthy-client/src/backchannel_logout/logout_token.rs
- rauthy-client/src/lib.rs
- rauthy-client/src/oidc_config.rs
- rauthy-client/src/provider.rs
- rauthy-client/src/scim/axum.rs
- rauthy-client/src/scim/mod.rs
- rauthy-client/src/scim/types.rs
- src/api/src/clients.rs
- src/models/src/entity/clients_scim.rs
- src/models/src/entity/scim_types.rs
- src/models/src/entity/users.rs
This PR brings the SCIM client side into the `rauthy-client` for easy usage when activating the new `scim` feature.
This is an incomplete SCIM impl on purpose to keep the complexity down. Only the Operations that Rauthy will use eventually are implemented to make everything work as expected.
For now, only API extractors for `axum` are added behind `scim` + `axum` feature.
> Feat: Add SCIM types + impl's to `rauthy-client`

- Cargo.lock
- Cargo.toml
- src/bin/Cargo.toml
- src/bin/src/main.rs
After having done tests with different memory allocators, Rauthy will be changed to use `jemalloc` on all non-MSVC platforms.
I tested both `jemalloc` and `mimalloc` against the default `malloc`. `jemalloc` has been significantly faster then `malloc` while having slightly higher memory usage spikes, but with less heap memory used overall because of less memory fragmentation. `mimalloc` was even a tiny bit faster than `jemalloc`, but with way higher memory spikes, so the best option is `jemalloc`.
I will build a nightly image with `jemalloc` and do some real world tests. Local memory profiling during development does not show the whole story.
> use `jemalloc` on non-MSVC platforms

- CONTRIBUTING.md
- justfile
As discussed in #944, here are:
- the `watch` command (based on [watchexec](https://watchexec.github.io/))
- renamed `backend-*` commands to `dev-env-*`
> Improve dev env commands

- migrations/hiqlite/13_remove_legacy_logo.sql
The old Rauthy logo is showing up for new deployments using Hiqlite and `v0.29`. The old logo has been delt with programmatically back then, when the new Logo was added with `0.28`, but a DB migration has been forgotten for later deployments like `0.29` now, when this temporary programmatic query does not exist anymore.
This adds a DB migration which will drop the logo. It may be the case, that users need to re-upload a custom logo, if they had a custom SVG now.
Merging this PR will be postponed until `0.30` to not have a breaking change now before any possible patch releases.
> Fix: add DB migration to drop a possibly left-over legacy rauthy logo

- src/bin/Cargo.toml
- src/bin/src/main.rs
Adds optional support for `jemalloc`.
For most use cases, the default `malloc` is more memory efficient than `jemalloc`. However, for instances with many users, it may be beneficial to custom compile Rauthy with the `jemalloc` feature enabled. This will use `jemalloc` as the global memory allocator. It uses more memory in idle or with low user counts (probably below 1000 users). However, depending on the scenario, I have seen up to 25% performance gains with `jemalloc`. This is especially true when allocating a lot of memory, which would happen for lots of concurrent requests.
This feature is disabled by default for now. `jemalloc` will not work on Windows MSVC targets.
> Feat: add `jemalloc` feature flag

- justfile
- rauthy.cfg
- src/api/src/openapi.rs
- src/api_types/src/api_keys.rs
- src/api_types/src/auth_providers.rs
- src/api_types/src/blacklist.rs
- src/api_types/src/clients.rs
- src/api_types/src/cust_validation.rs
- src/api_types/src/events.rs
- src/api_types/src/fed_cm.rs
- src/api_types/src/generic.rs
- src/api_types/src/groups.rs
- src/api_types/src/oidc.rs
- src/api_types/src/roles.rs
- src/api_types/src/scopes.rs
- src/api_types/src/sessions.rs
- src/api_types/src/themes.rs
- src/api_types/src/users.rs
- src/common/src/lib.rs
- src/models/src/entity/scopes.rs
#836
Clean up unnecessary `derive` impls and split into prod / dev to reduce release binary size.
> Cleanup unnecessary `derive`s on different types

- justfile
- src/bin/Cargo.toml
After a lot of testing, `jemalloc` will now be used as the default allocator on all platforms except windows msvc.
It has slightly higher memory usage after a fresh restart, but less after real usage and no fragmentation issues.
It also makes it possible to specific tuning.
> Feat: use `jemalloc` as the defautl allocator

- Cargo.lock
- book/src/config/config.md
- book/src/config/tuning.md
- dev_notes.md
- frontend/package-lock.json
- frontend/src/lib/admin/attrs/AttrConfig.svelte
- frontend/src/lib/admin/config/argon2/Argon2Params.svelte
- frontend/src/lib/admin/documentation/Documentation.svelte
- frontend/vite.config.js
- rauthy.cfg
- src/api/Cargo.toml
- src/api/src/lib.rs
- src/api/src/swagger_ui.rs
- src/bin/src/main.rs
- src/bin/src/server.rs
This PR get's rid of probably the biggest issue that came up lately regarding to memory usage. After a lot of debugging and memory profiling, I found out that the external `SwaggerUI` has a quite big issue. It contains the `openapi.json` and does a deep copy of the whole data into each HTTP worker thread, instead of keeping it behind a reference. For smaller API, you won't notice it that much, but in Rauthy's case, this data takes up ~13 MB of memory. If you then started 16 HTTP workers, it would mean that Rauthy used 16x 13MB of memory just for serving API docs, which is absolutely ridiculous.
To counter this, and to solve another issue I had on my TODO for a long time, I created endpoints to serve this data manually and pushed the config into static memory upfront, which now concurrent …
> Feat: push `SwaggerUI` into static memory

- frontend/package.json
Because of the addition of setting env vars in front of the build command, it broke compiling under Windows.
https://www.npmjs.com/package/cross-env?activeTab=readme
> fix windows build, add cross-env to package.json

- Cargo.lock
- Cargo.toml
- src/models/src/entity/jwk.rs
Small bugfix for the public JWKS.
After the recent rework of the whole JWT setup, the EdDSA public keys have been exposed incorrectly. They were base64 encoded DER format, when it should have been base64 encoded raw bytes. This made decoding the public keys in a client fail of course.
> Fix: encoding for EdDSA public key

- rauthy-client/src/backchannel_logout/logout_token.rs
The `rauthy-client` has not been migrated to our own custom JWT implementation and the `sub` in LogoutTokens was sometimes not correctly deserialized, when there was no `sid`, becaue of the way `jwt-simple` works, which the client still uses.
> rauthy-client: fix `LogoutToken.sub` not being deserialized correctly

- src/schedulers/src/sessions.rs
The sessions cleanup scheduler cleans up expired sessions. However, it makes a lot of sense to include timed-out sessions as well, even when they have not expired yet.
> include timed-out sessions in cleanup scheduler

- CHANGELOG.md
- src/models/src/vault_config.rs
- vault.toml
An end-user should never care about `DEV_MODE` env var to do anything. The value you need to set to allow insecure vault connections is now `DANGER_VAULT_INSECURE` to make it a lot clearer that this is dangerous and should never be used in production.
> Fix: change the way to allow vault insecure connections

- src/api/src/users.rs
- src/models/src/entity/webauthn.rs
- src/service/src/oidc/authorize.rs
An additional improvement to Login location checks.
Locations are checked with each successful MFA auth request, even when it's a Test / Service request only. These can only be done with a valid session and they could highlight stolen session information, if for instance a users browser got compromised with all data stolen, and then the additional IP validation has been disabled.
Rauthy now also checks the login location after a password has been successfully compared, even if the account is secure further with MFA, which an attacker might not be able to break. It would not be a full account compromise and technically not a real login from a new location, but it would notify users about stolen passwords, so they can be changed, even if all of their data was untouched because of still …
> Feat: further improve login location checks

- frontend/src/css/theme.css
- frontend/src/lib/ThemeSwitch.svelte
Permanently overwriting the theme in the UI via the theme switcher button was not working as expected under certain conditions. The value has not been persisted correctly in some cases.
This PR fixes the overwriting of otherwise set system prefs and actually persists them between reloads.
> Fix: UI theme overwrite

- Dockerfile_builder
#1107
These additional dependencies make it possible to re-use the same builder image for the `rauthy-pam-nss` project.
> include PAM build deps in `Dockerfile_builder`

- Cargo.lock
- Cargo.toml
This would simplify packaging Rauthy with Nix, as the swagger files will be downloaded when the crates are fetched, rather than at build time (when Nix disallows internet access to ensure reproducibility).
> Add vendored feature for utoipa-swagger-ui
