sebadob/rauthy

frontend/src/components/account/AccEdit.svelte
frontend/src/lib/Button.svelte
frontend/src/lib/Loading.svelte

- show loading indicator on account edit page when changing passwords (takes some time)
- possible animation fade fix for loading indicator inside buttons
- switch loading component animation from JS to CSS

Loading indicator account page

---

Cargo.lock
rauthy-common/Cargo.toml
rauthy-common/src/constants.rs
rauthy-common/src/error_response.rs
rauthy-common/src/utils.rs
rauthy-handlers/src/openapi.rs
rauthy-models/Cargo.toml
rauthy-models/src/entity/clients.rs
rauthy-models/src/entity/dpop_proof.rs
rauthy-models/src/entity/jwk.rs
rauthy-models/src/entity/mod.rs
rauthy-models/src/migration/db_migrate.rs
rauthy-models/src/request.rs
rauthy-models/src/response.rs
rauthy-service/src/auth.rs
rauthy-service/src/client.rs

This implements the basics for solving #132.
The issue will be completed over 2-3 smaller PR's.
This one implements the basics which we then can build upon.

Impl DPoP basics

---

Cargo.lock
Cargo.toml
rauthy-handlers/src/oidc.rs
rauthy-handlers/src/openapi.rs
rauthy-main/Cargo.toml
rauthy-main/src/main.rs
rauthy-main/tests/handler_auth.rs
rauthy-main/tests/zza_handler_cust_attrs.rs
rauthy-main/tests/zzc_handler_clients.rs
rauthy-models/Cargo.toml
rauthy-models/src/app_state.rs
rauthy-models/src/entity/dpop_proof.rs
rauthy-models/src/entity/jwk.rs
rauthy-models/src/lib.rs
rauthy-models/src/request.rs
rauthy-models/src/response.rs
rauthy-service/src/auth.rs
rauthy-service/src/token_set.rs

This should make #132 work and make Rauthy ready for some first real world DPoP tests.
There are some minor open questions and code is not optimized yet. First goal is to make it work properly and correctly.

Use dpop and create integrations tests

---

rauthy-common/src/constants.rs
rauthy-common/src/error_response.rs
rauthy-handlers/src/oidc.rs
rauthy-main/src/main.rs
rauthy-main/tests/handler_auth.rs
rauthy-models/src/entity/dpop_proof.rs
rauthy-models/src/entity/principal.rs
rauthy-service/src/auth.rs
rauthy.cfg

This should "complete" the DPoP nonce feature for #132

Impl dpop nonces

---

rauthy-models/src/events/health_watch.rs

This fixes a logic bug with the health watcher if rauthy is running in HA mode but has an unhealthy cache layer

fix health watcher in HA mode

---

rauthy-common/src/constants.rs
rauthy-models/src/entity/clients.rs
rauthy-models/src/events/health_watch.rs
rauthy-models/src/request.rs

This is the first step in the direction of making ephemeral clients with Solid OIDC work

Impl ephemeral client request

---

rauthy-main/src/schedulers.rs

This is a small improvement for the App version update watcher.
It should only send out a notification about a new version once after a restart.

only send out a notification about a new app version once after a restart

---

rauthy-models/src/entity/sessions.rs
rauthy-models/src/entity/users.rs

When a user with an existing, valid session was being deleted by an admin while he was logged in, the cache eviction of the sessions did not work correctly. The user would not get redirected to the login page but would actually see a technical error from the backend.
This was no security issue. It just looked very ugly for that deleted user.

impl Session::delete_by_user()

---

migrations/postgres/14_user_attr_values_fk_fix.sql
migrations/sqlite/14_user_attr_values_fk_fix.sql

Add a foreign key constraint on `user_attr_values` - `user_id` and cascade deletions from the `users` table

Add an FK constraint for `user_attr_values` and cascade on user deletion

---

rauthy-handlers/src/events.rs
rauthy-main/src/main.rs
rauthy-models/src/events/event.rs
rauthy-models/src/request.rs

This is a preparation for the new events section in the UI to fetch historic events from the database.

Historic events api endpoint

---

Cargo.toml
rauthy-book/src/config/config.md
rauthy-main/src/main.rs
rauthy-models/src/migration/mod.rs
rauthy.cfg

This makes restoring SQLite backups either from file or S3 storage possible via rust setting `RESTORE_BACKUP`.

Auto restore sqlite backups

---

Cargo.lock
Cargo.toml
dev_notes.md
rauthy-main/src/main.rs
rauthy-models/src/entity/users.rs

- check the current E-Mail entries in the DB and convert everything to lowercase if necessary
- before creating or updating any user, not matter in which way, always convert any E-Mail address to lowercase
- make some E-Mail checks more user friendly by comparing as lowercase only

Always convert emails to lowercase

---

Cargo.lock
Cargo.toml
dev_notes.md
frontend/src/components/account/AccEdit.svelte
frontend/src/components/admin/users/UserInfo.svelte
frontend/src/components/admin/users/UserTile.svelte
frontend/src/components/admin/users/Users.svelte
frontend/src/routes/account/+page.svelte
frontend/src/utils/constants.js
migrations/postgres/15_users_values.sql
migrations/sqlite/15_users_values.sql
rauthy-book/src/config/config.md
rauthy-common/src/constants.rs
rauthy-handlers/src/openapi.rs
rauthy-handlers/src/users.rs
rauthy-main/src/main.rs
rauthy-main/tests/handler_users.rs
rauthy-main/tests/zzb_handler_password_policy.rs
rauthy-models/src/entity/jwk.rs
rauthy-models/src/entity/mod.rs
rauthy-models/src/entity/user_attr.rs
rauthy-models/src/entity/users.rs
rauthy-models/src/entity/users_values.rs
rauthy-models/src/entity/webids.rs
rauthy-models/src/i18n/account.rs
rauthy-models/src/language.rs
rauthy-models/src/request.rs
rauthy-models/src/response.rs
rauthy.cfg
rauthy.test.cfg

This PR is about adding additional optional values for each user which can be self-managed.
These are usefuly values from the OIDC default claims.

Additional user custom values

---

frontend/src/components/admin/events/Event.svelte
frontend/src/lib/itemTiles/ItemTiles.svelte

This is about fixing some smaller visual bugs in the UI

Small UI fixes

---

rauthy-main/src/main.rs

Fix the startup crash when v0.20 is used for a fresh new install

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
frontend/package-lock.json
justfile
rauthy.cfg

Build nightly images to properly test the impl for #245

Update deps and build nightly images

---

rauthy-main/src/schedulers.rs

This fixes a small bug with the latest Rauthy version link in the UI, if an update is available.

fix latest version link if an update is available

---

rauthy-models/src/entity/well_known.rs

This is a small fix to properly include the `registration_endpoint` url in the `.well-known/openid-configration` if dynamic client registration is enabled. This will make sure, that any auto setup and discovery will work.

fix: include `registration_endpoint` in openid config if `ENABLE_DYN_CLIENT_REG=true`

---

justfile

This ended up being the fix
https://stackoverflow.com/questions/12272065/sed-undefined-label-on-macos
Now I don't know if you would want a seperate just command for macs in particular or if there's cleaner way to specify it. But let me know!
Thanks!

build ui mac fix

---

rauthy-client/src/provider.rs

rauthy-client: remove http2 prior knowledge from client for better compatibility

---

frontend/src/components/admin/clients/ClientConfig.svelte
frontend/src/lib/inputs/Input.svelte

Fixes a bug in the UI where the input for client name can contain `undefined` if the name has been deleted and saved after there was an existing one.

bug: UI `client_name` showing undefined

---

rauthy-models/src/email.rs
rauthy-models/src/i18n/email_password_new.rs
rauthy-models/src/i18n/mod.rs

custom template text for new password set

---

frontend/src/routes/users/register/+page.svelte
frontend/src/routes/users/{id}/reset/reset/+page.svelte
rauthy-handlers/src/users.rs
rauthy-models/src/entity/magic_links.rs
rauthy-models/src/entity/users.rs
rauthy-models/src/i18n/password_reset.rs
rauthy-models/src/request.rs
rauthy-service/src/password_reset.rs

Custom `redirect_uri` for user registration form

---

Cargo.lock
Cargo.toml
dev_notes.md
rauthy-book/src/config/config.md
rauthy-models/Cargo.toml
rauthy-models/src/email.rs
rauthy-models/src/entity/users.rs
rauthy-models/src/i18n/email_password_new.rs
rauthy-models/src/i18n/email_reset.rs
rauthy.cfg
templates/email/reset.html
templates/email/reset.txt

custom template password i18n overwrites

---

docs/auth_providers/github.html
docs/auth_providers/index.html
justfile

...and commit missing docs files manually

fix `build-docs` recipe to always add all files after new build

---

Cargo.lock
rauthy-client/examples/actix-web/Cargo.lock
rauthy-client/examples/axum/Cargo.lock
rauthy-client/examples/generic/Cargo.lock

fix https://rustsec.org/advisories/RUSTSEC-2024-0336.html

bump rustls everywhere to fix potential DoS in rustls

---

frontend/src/utils/dataFetching.js
rauthy-common/src/constants.rs
rauthy-handlers/src/generic.rs
rauthy-handlers/src/openapi.rs
rauthy-handlers/src/users.rs
rauthy-main/src/main.rs

fix: PoW CORS

---

rauthy-handlers/src/users.rs

Really a minor thing, we was confused when we looked into the swagger ui. :D

fix: minor documentation, request body for /users/register

---

rauthy-common/src/constants.rs
rauthy-handlers/src/generic.rs
rauthy-main/src/main.rs
rauthy-models/src/entity/users.rs
rauthy-models/src/request.rs
rauthy-models/src/response.rs

This PR is a preparation feature to make Server Side Pagination work in the future. This will be necessary for bigger instances that have probably >10k users to keep the UI fast.

feat: create a new `/search` endpoint for future server side pagination

---

CHANGELOG.md
frontend/src/lib/icons/IconHome.svelte
frontend/src/routes/oidc/authorize/+page.svelte
frontend/src/routes/users/register/+page.svelte
justfile
rauthy-handlers/src/oidc.rs
rauthy-models/src/i18n/authorize.rs

fixes #308
Prerequisite work has been done with the release of v0.22 already, so we can show now a "client home page" during login, if this data exists. We also can show a link to the user registration below the login form, if it is open.

UI: show additional client info + user reg during login

---

rauthy-main/src/schedulers.rs

devices cleanup scheduler

---

CHANGELOG.md
frontend/src/lib/Button.svelte

fix misplaces button labels with chrome

---

CHANGELOG.md
frontend/src/components/account/AccInfo.svelte
rauthy-handlers/src/oidc.rs

fix: openapi desc

---

frontend/src/routes/users/register/+page.svelte

UI: redirect after user registration

---

frontend/src/components/account/AccModPwd.svelte
frontend/src/components/admin/users/UserPassword.svelte
frontend/src/routes/oidc/authorize/+page.svelte
frontend/src/routes/users/{id}/reset/reset/+page.svelte
rauthy-models/src/entity/continuation_token.rs
rauthy-models/src/entity/groups.rs
rauthy-models/src/entity/jwk.rs
rauthy-models/src/entity/magic_links.rs
rauthy-models/src/entity/roles.rs
rauthy-models/src/entity/scopes.rs
rauthy-models/src/entity/user_attr.rs
rauthy-models/src/entity/users.rs
rauthy-models/src/language.rs
rauthy-models/src/lib.rs
rauthy-models/src/request.rs
rauthy-models/src/templates.rs
rauthy-service/src/auth.rs

fix: too strict password input validation on `/authorize`

---

frontend/src/routes/oidc/authorize/+page.svelte
justfile

feat: build `redirect_uri` on `/authorize` if `client_uri` exists

---

frontend/src/components/admin/clients/Clients.svelte
frontend/src/components/admin/roles/Roles.svelte
frontend/src/components/admin/scopes/Scopes.svelte
frontend/src/components/admin/userAttr/Attr.svelte
frontend/src/components/admin/users/Users.svelte
frontend/src/lib/search/OrderSearchBar.svelte
frontend/src/lib/search/SearchBar.svelte

fix: reset the search input on any site if data is being refetched

---

Cargo.lock
frontend/src/components/admin/users/Users.svelte
frontend/src/lib/search/SearchBar.svelte
justfile
rauthy-models/src/entity/users.rs
rauthy-models/src/response.rs
rauthy.cfg

feat: sort users created login

---

frontend/src/components/admin/providers/ProviderTileAddNew.svelte

correctly reset provider add values on template switch

---

frontend/src/components/admin/providers/ProviderTileAddNew.svelte

Adds additional checks on the client side for required input fields.  
Also, some inputs have been changed to enable autocomplete, but this still creates problems in some cases and is not properly working. The autocomplete fix has been postponed for now, since this might be resolved automatically with the migration to a new UI anyway.
fixes #466

UI: improve UX for provider config

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/api/src/oidc.rs
src/api/src/openapi.rs
src/api_types/src/oidc.rs
src/models/src/lib.rs
src/service/src/oidc/token_info.rs

`/introspect` enhancements

---

CHANGELOG.md
src/api/src/fed_cm.rs
src/bin/tests/handler_auth.rs
src/models/src/entity/jwk.rs
src/models/src/lib.rs
src/service/src/oidc/grant_types/authorization_code.rs
src/service/src/oidc/grant_types/device_code.rs
src/service/src/oidc/grant_types/password.rs
src/service/src/oidc/validation.rs
src/service/src/token_set.rs

fix: `auth_time` in `id_token` on refresh

---

justfile

- Only install missing tools when setup.
- podman compatibility
- pnpm compatibility

Some justfile improvments

---

Cargo.lock
Cargo.toml
Dockerfile

fix: revert container user change

---

frontend/src/components/admin/users/UserInfo.svelte

feat: show `User.created_at` in admin ui

---

src/api/src/auth_providers.rs
src/api/src/clients.rs
src/api/src/oidc.rs
src/api/src/users.rs

fix: OpenAPI response body definitions in some places

---

CHANGELOG.md
Cargo.lock
Cargo.toml
frontend/src/components/admin/providers/JsonPathDesc.svelte
frontend/src/components/admin/providers/ProviderConfig.svelte
frontend/src/components/admin/providers/ProviderTileAddNew.svelte
migrations/hiqlite/3_client_auth_methods.sql
migrations/postgres/29_client_auth_methods.sql
src/api/src/auth_providers.rs
src/api_types/src/auth_providers.rs
src/models/src/entity/auth_providers.rs

feat: configure upstream IdP client_auth_method

---

frontend/src/utils/constants.js
src/api_types/src/generic.rs
src/models/src/entity/well_known.rs
src/models/src/i18n/account.rs
src/models/src/i18n/authorize.rs
src/models/src/i18n/device.rs
src/models/src/i18n/email_change_info_new.rs
src/models/src/i18n/email_change_info_old.rs
src/models/src/i18n/email_confirm_change.rs
src/models/src/i18n/email_confirm_change_html.rs
src/models/src/i18n/email_password_new.rs
src/models/src/i18n/email_reset.rs
src/models/src/i18n/email_reset_info.rs
src/models/src/i18n/error.rs
src/models/src/i18n/index.rs
src/models/src/i18n/logout.rs
src/models/src/i18n/password_policy.rs
src/models/src/i18n/password_reset.rs
src/models/src/i18n/register.rs
src/models/src/language.rs

Add Korean i18n support for Rauthy.

Add Korean i18n

---

rauthy-client/examples/axum/Cargo.lock
rauthy-client/examples/axum/src/main.rs
rauthy-client/src/principal/axum.rs

fix: OptionalFromRequestParts extraction for rauthy-client

---

Cargo.lock
Cargo.toml
dev_notes.md
src/api/Cargo.toml
src/api/src/api_keys.rs
src/api/src/auth_providers.rs
src/api/src/blacklist.rs
src/api/src/clients.rs
src/api/src/events.rs
src/api/src/fed_cm.rs
src/api/src/generic.rs
src/api/src/groups.rs
src/api/src/oidc.rs
src/api/src/roles.rs
src/api/src/scopes.rs
src/api/src/sessions.rs
src/api/src/users.rs
src/error/src/error_impls.rs

drop `actix-web-validator`

---

justfile

fix: remove `just` from `setup` and fix `cargopkgs` check

---

frontend/src/components/admin/userAttr/Attr.svelte

fix: update UI content if the last custom attr has been deleted

---

src/models/src/entity/api_keys.rs
src/models/src/entity/auth_codes.rs
src/models/src/entity/clients.rs
src/models/src/entity/dpop_proof.rs
src/models/src/entity/jwk.rs
src/models/src/entity/magic_links.rs
src/models/src/entity/refresh_tokens.rs
src/models/src/entity/refresh_tokens_devices.rs
src/models/src/entity/sessions.rs
src/models/src/entity/users.rs
src/models/src/entity/webauthn.rs

feat: manual `Debug` impl for sensitive data

---

Cargo.lock
Cargo.toml

[CWE-770](https://cwe.mitre.org/data/definitions/770.html) in `ring` under certain conditions.

fix: `ring` - CWE-770

---

frontend/src/lib/admin/roles/RoleConfig.svelte

fix: label for role name input in admin UI

---

frontend/src/lib/admin/providers/ProviderAddNew.svelte
frontend/src/lib/admin/providers/ProviderConfig.svelte
frontend/src/lib/admin/providers/blocks/ProviderConfigClientInfo.svelte
frontend/src/lib/admin/providers/blocks/ProviderConfigRootCA.svelte
frontend/src/lib/admin/providers/blocks/ProviderConfigURLs.svelte

fix: duplicate `insecure TLS` checkbox + restructure provider add new + config components

---

frontend/src/lib/account/AccWebId.svelte
frontend/src/lib/admin/api_keys/ApiKeyAddNew.svelte
frontend/src/lib/admin/api_keys/ApiKeyConfig.svelte
frontend/src/lib/form/Input.svelte
frontend/src/lib/form/InputArea.svelte
frontend/src/lib/form/InputDate.svelte
frontend/src/lib/form/InputPassword.svelte
frontend/src/lib/form/InputTime.svelte

fix: `<Input>` validation on re render

---

frontend/src/lib/admin/users/UserInfo.svelte

fix: ui: groups in `<UserInfo>` containing roles

---

frontend/src/lib/admin/users/UserAddNew.svelte
frontend/src/routes/oidc/callback/+page.svelte

Fix: UI: do not send `expires` during  user creation via admin UI if unchecked

---

src/schedulers/src/magic_links.rs

Fix: include `webauthn_user_id` check in unused magic link expiry cleanup scheduler

---

src/models/src/email.rs

return inner error after SMTP connection failures, if it exists

---

src/api/src/dev_only.rs
src/api/src/oidc.rs

feat: make RP initiated logout possible via `GET /logout`

---

CONTRIBUTING.md

docs: add `FreeBSD` section to `CONTRIBUTING.md`

---

CONTRIBUTING.md
src/models/src/html/templates.rs

docs: update `CONTRIBUTING.md` and add `warn!` for `tpl_password_reset`

---

src/bin/src/main.rs

refer to the detailed documentation for `ENC_KEYS` instead of getting started on error

---

src/models/src/entity/clients_scim.rs
src/models/src/entity/scim_types.rs

feat: build `Scim::PatchOp` jsons manually to greatly reduce number of allocations

---

frontend/src/i18n/admin/de.ts
frontend/src/i18n/admin/en.ts
frontend/src/i18n/admin/interface.ts
frontend/src/i18n/admin/ko.ts
frontend/src/lib/admin/users/UserPassword.svelte

Feat: make it possible to manually initialize a new user via the Admin UI

---

frontend/src/lib/admin/api_keys/ApiKeys.svelte
frontend/src/lib/admin/attrs/Attributes.svelte
frontend/src/lib/admin/blacklist/Blacklist.svelte
frontend/src/lib/admin/clients/Clients.svelte
frontend/src/lib/admin/events/Events.svelte
frontend/src/lib/admin/events/EventsArchive.svelte
frontend/src/lib/admin/groups/Groups.svelte
frontend/src/lib/admin/providers/Providers.svelte
frontend/src/lib/admin/roles/Roles.svelte
frontend/src/lib/admin/scopes/Scopes.svelte
frontend/src/lib/admin/sessions/SessionRow.svelte
frontend/src/lib/admin/sessions/Sessions.svelte
frontend/src/lib/admin/users/Users.svelte

Fix: not correctly overflowing nav lists - missing scrollbars

---

frontend/src/lib/admin/blacklist/Blacklist.svelte

I believe this was added in 9bbbb8d by accident.

remove erroneous character

---

src/models/src/entity/sessions.rs

Fix: Session validation with `SESSION_VALIDATE_IP`

---

src/bin/src/main.rs

add read error to `eprintln` on `rauthy.cfg` errors

---

src/models/src/entity/theme.rs
src/models/src/migration/db_migrate.rs
src/models/src/migration/inserts.rs

Fix: DB migration queries

---

frontend/src/lib/admin/providers/blocks/ProviderConfigClientInfo.svelte

UI: Fix form validation for auth provider conig

---

src/models/src/migration/inserts.rs

Fix: use correct execute query for migrating auth providers

---

frontend/src/api/types/user_attrs.ts
frontend/src/i18n/admin/de.ts
frontend/src/i18n/admin/en.ts
frontend/src/i18n/admin/interface.ts
frontend/src/i18n/admin/ko.ts
frontend/src/lib/admin/attrs/AttrConfig.svelte
frontend/src/lib/admin/users/UserAttr.svelte
frontend/vite.config.js
migrations/hiqlite/15_user_attr_config_feat.sql
migrations/postgres/V10__user_attr_config_feat.sql
src/api/src/openapi.rs
src/api/src/users.rs
src/api_types/src/users.rs
src/bin/tests/zza_handler_cust_attrs.rs
src/models/src/entity/user_attr.rs
src/service/src/token_set.rs

Feat: make it possible to define default values for custom user attributes

---

frontend/src/lib/admin/users/UserDetails.svelte
frontend/src/lib/admin/users/UserInfo.svelte
frontend/src/lib/admin/users/Users.svelte
src/models/src/entity/user_attr.rs

Feat: show user acc type + upstream IdP in admin UI

---

Cargo.toml
src/bin/src/dummy_data.rs
src/bin/src/init_lazy_vars.rs
src/bin/src/main.rs
src/bin/src/server.rs
src/common/src/compression.rs
src/common/src/constants.rs
src/common/src/password_hasher.rs
src/common/src/utils.rs
src/models/src/email.rs

The very early init of most lazy static's that will be used at some point has 2 advantages:
- better UX because an early panic if a bad configuration has been given instead of "some time later" when the value is needed the first time
- very compact beginning of the Heap leads to less memory fragmentation later on

Feat: initialize most lazy vars as early as possible

---

src/models/src/rauthy_config.rs

Fix: remove leftover `#[cfg(debug_assertions)]`

---

Cargo.toml
config.toml
dev_notes.md
frontend/src/api/types/user.ts
frontend/src/i18n/common/en.ts
frontend/src/lib/account/AccEdit.svelte
frontend/src/lib/admin/users/UserInfo.svelte
frontend/src/routes/device/+page.svelte
frontend/src/utils/patterns.ts
migrations/hiqlite/16_zip_to_string.sql
migrations/postgres/V11__zip_to_str.sql
src/api_types/src/oidc.rs
src/api_types/src/users.rs
src/bin/src/main.rs
src/jwt/src/claims.rs
src/models/src/entity/auth_providers.rs
src/models/src/entity/scim_types.rs
src/models/src/entity/users.rs
src/models/src/entity/users_values.rs

change `zip` into a `String`

---

config.toml
frontend/src/api/types/authorize.ts
frontend/src/i18n/common/de.ts
frontend/src/i18n/common/en.ts
frontend/src/i18n/common/interface.ts
frontend/src/i18n/common/ko.ts
frontend/src/i18n/common/zh.ts
frontend/src/routes/oidc/authorize/+page.svelte
frontend/src/routes/users/password_reset/+page.svelte
frontend/vite.config.js
src/api/src/html.rs
src/api/src/users.rs
src/api_types/src/users.rs
src/bin/src/server.rs
src/models/src/email.rs
src/models/src/entity/groups.rs
src/models/src/html/mod.rs
src/models/src/html/templates.rs
src/models/src/i18n_email/reset.rs
src/models/src/rauthy_config.rs
templates/email/base.html
templates/email/reset.html
templates/email/reset.txt

Adds a dedicated password reset request page which can be appended to magic link emails, so users have a direct link to request a new magic link, if the current one has expired.

Feat: dedicated password page

---

src/api_types/src/oidc.rs

fixes #974 (for real this time)

Fix: too strict validation for the `state` param

---

src/models/src/email.rs

trigger a graceful DB shutdown before SMTP retry panic

---

src/models/src/rauthy_config.rs

ddd a scheme check for `pub_url` to `Vars::validate()`

---

src/models/src/database.rs
src/models/src/entity/clients_scim.rs
src/models/src/migration/db_migrate.rs
src/models/src/migration/inserts.rs

Some of the latest features and changes have been missing in DB migrations between databases.

Fix: missing DB migrations

---

src/models/src/migration/init_prod.rs

Fix: RS256 key modulus during init prod as well

---

src/api/src/pam.rs
src/api_types/src/pam.rs
src/bin/src/server.rs
src/models/src/entity/pam/hosts.rs

Feat: `whoami` endpoint for PAM hosts

---

frontend/src/api/types/pam.ts
frontend/src/i18n/admin/de.ts
frontend/src/i18n/admin/en.ts
frontend/src/i18n/admin/interface.ts
frontend/src/i18n/admin/ko.ts
frontend/src/i18n/common/de.ts
frontend/src/i18n/common/en.ts
frontend/src/i18n/common/interface.ts
frontend/src/i18n/common/ko.ts
frontend/src/i18n/common/zh.ts
frontend/src/lib/account/AccPAM.svelte
frontend/src/lib/search_bar/SearchBar.svelte
src/api/src/pam.rs
src/api_types/src/pam.rs
src/bin/src/server.rs
src/models/src/entity/pam/hosts.rs

Feat: show PAM hosts with access in account dashboard

---

src/models/src/rauthy_config.rs
src/models/src/vault_config.rs

parse env vars even if base table does not exist in toml

---

Cargo.lock
Cargo.toml

bump `hiqlite` + `cryptr` to allow `:` in `EncKeyId` regex

---

CONTRIBUTING.md
frontend/src/utils/constants.ts

Updates some things in CONTRIBUTING.md that have been changed in the last weeks.

Doc: updates to CONTRIBUTING.md
